---
- name: Reset website for demonstration purposes.
  hosts: linuxone
  become: true
  tasks:

    - name: Modify firewalld to not allow tcp connections via port 80.
      ansible.posix.firewalld:
        service: http
        permanent: true
        immediate: true
        state: disabled

    - name: Stop and disable firewalld.
      ansible.builtin.service:
        name: firewalld
        state: stopped
        enabled: false

    - name: Remove /var/www/html/index.html from server.
      ansible.builtin.file:
        path: /var/www/html/index.html
        state: absent

    - name: Stop and disable httpd.
      ansible.builtin.service:
        name: httpd
        state: stopped
        enabled: false

    - name: Ensure httpd package is absent.
      ansible.builtin.package:
        name: httpd
        state: absent
