---
- name: Deploy simple website using Ansible Lightspeed for demonstration purposes.
  hosts: linuxone
  become: true
  tasks:
    - name: Ensure httpd package is installed.
    - name: Start and enable firewalld.
    - name: Modify firewalld to allow tcp connections via port 80.
    - name: Copy contents from site folder and set permissions and ownership to root.
    - name: Start and enable httpd.
    - name: Print IP address for web server using Ansible facts.
