---
- name: Deploy webserver
  hosts: linuxone
  tasks:
    - name: Ensure firewalld and httpd are installed
      ansible.builtin.package:
        name:
          - firewalld
          - httpd
        state: present

    - name: Ensure firewalld and httpd are started and enabled
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - firewalld
        - httpd

    - name: Ensure firewalld allows httpd
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true

    - name: Copy website contents
      ansible.builtin.copy:
        src: site/
        dest: /var/www/html/
        mode: '644'
        owner: apache
        group: apache

    - name: Restart firewalld and httpd
      ansible.builtin.service:
        name: "{{ item }}"
        state: restarted
      loop:
        - firewalld
        - httpd
