---
- name: Deploy webserver via ansible
  hosts: linuxone
  become: true
  tasks:

    - name: Install httpd and firewalld packages
      ansible.builtin.package:
        name:
          - httpd
          - firewalld
        state: present

    - name: Ensure firewalld and httpd are started and enabled
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - firewalld
        - httpd

    - name: Ensure firewalld allows http
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true

    - name: Copy website contents from site folder and set permissions correctly
      ansible.builtin.copy:
        src: site/
        dest: /var/www/html/
        owner: apache
        group: apache
        mode: '755'

    - name: Restart firewalld and httpd
      ansible.builtin.service:
        name: "{{ item }}"
        state: restarted
      loop:
        - firewalld
        - httpd
