---
- name: Deploy webserver for linuxone group
  hosts: linuxone
  become: true
  tasks:
    - name: Install httpd and firewalld
      ansible.builtin.package:
        name:
          - httpd
          - firewalld
        state: present
    - name: Copy website contents to /var/www/html
      ansible.builtin.copy:
        src: site/
        dest: /var/www/html/
        owner: root
        group: root
        mode: "0644"
    - name: Set firewall rules
      ansible.posix.firewalld:
        service: 80/tcp
        permanent: true
        state: enabled
        immediate: true
    - name: Restart httpd and firewalld
      ansible.builtin.service:
        name: "{{ item }}"
        state: restarted
        enabled: true
      loop:
        - httpd
        - firewalld

    - name: Check httpd service status
      ansible.builtin.service_facts:
      register: service_facts

    - name: Display httpd service status
      ansible.builtin.debug:
        msg: "httpd service status: {{ service_facts.ansible_facts.services['httpd.service'].state }}"
