---
- name: Deploy a simple website using Ansible Lightspeed with IBM watsonx Code Assistant for demonstration purposes.
  hosts: linuxone #try rhel or ubuntu too, to see changes to generated tasks.
  become: true
  tasks:
    - name: Ensure apache package is installed.
    - name: Start and enable firewalld.
    - name: Modify firewalld to allow tcp connections via port 80.
    - name: Copy contents from site folder and set permissions and ownership to root.
    - name: Start and enable httpd.
    - name: Print IP address for web server using Ansible facts.